version: '3'

services:
    db_server:
        image: mysql:${MYSQL_IMAGE_VERSION}
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            TZ: ${TIME_ZONE}
        volumes:
            - ./mysql/data:/var/lib/mysql:rw
            - ./mysql/web.sql:/docker-entrypoint-initdb.d/web.sql:ro
            - ./mysql/tlbbdb.sql:/docker-entrypoint-initdb.d/tlbbdb.sql:ro
        ports:
            - "3306:3306"
        container_name: db_server
        hostname: db_server
        
    game_server:
        image: liuguangw/game_server:latest
        restart: always
        volumes:
            - ./home:/home:rw
        working_dir: /home
        environment:
            TZ: ${TIME_ZONE}
            DB_PASSWORD: "${DB_PASSWORD}"
            GAME_SERVER_IP: ${GAME_SERVER_IP}
        ports:
            - "${GAME_SERVER_PORT}:7384"
            - "3731:3731"
        cap_add:
            - ALL
        privileged: true
        container_name: game_server
        hostname: game_server